# Generated by Django 3.0 on 2021-04-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0008_auto_20210427_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='')),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.UserPro')),
            ],
        ),
    ]
